\documentclass[11pt,a4paper,oneside]{article}
\usepackage{amsmath,amsthm,amsfonts,amssymb}
\usepackage{pst-eucl,pstricks,pstricks-add}
%\usepackage[utf8]{inputenc}
%\usepackage[latin1]{inputenc}
\usepackage[spanish,activeacute]{babel}
\usepackage[a4paper,margin=2.5cm]{geometry}
\usepackage{times}
\usepackage[T1]{fontenc}
\usepackage{titlesec}
\usepackage{color}
\usepackage{url}
\usepackage{float}
\usepackage{cite}
\usepackage{graphicx}
\usepackage{multicol}
\usepackage{float}
\usepackage{lmodern}
\parindent=0mm

\newenvironment{question}{\item}{}
\newenvironment{solution}{\comment}{\endcomment}
\newenvironment{answerlist}{\renewcommand{\labelenumi}{(\alph{enumi})}\begin{enumerate}}{\end{enumerate}}


\begin{document}

\thispagestyle{empty}
{\sf
{\Large \scshape Escuela Polit\'{e}cnica Nacional} \hfill {\scshape C\'{a}lculo en una variable}\\[7mm]
{\scshape Nombre:} \rule{0.6\textwidth}{0.5pt}\qquad {\scshape Nro. lista:} \rule{0.1\textwidth}{0.5pt}\\
}

<<ejercicio01, echo=FALSE, results='hide'>>=
one <- list()

if (runif(1) < 0.25) {
      one$a <- c("3","-10","+7")
} else if (runif(1) >= 0.25 & runif(1) < 0.5) {
      one$a <- c("2","-16","+24")
} else if (runif(1) >= 0.5 & runif(1) < 0.75) {
      one$a <- c("6","-5","-6")
} else {
      one$a <- c("4","+11","-3")
}

if (runif(1) < 0.25) {
      one$b <- c("125","-27")
} else if (runif(1) >= 0.25 & runif(1) < 0.5) {
      one$b <- c("64","+1")
} else if (runif(1) >= 0.5 & runif(1) < 0.75) {
      one$b <- c("8","+27")
} else {
      one$b <- c("27","-64")
}

#orden <- sample(1:3)
#one <- one[orden]
@

<<ejercicio02, echo=FALSE, results='hide'>>=
two <- list()

if (runif(1) < 0.25) {
      two$a <- c("-5","+3","2")
} else if (runif(1) >= 0.25 & runif(1) < 0.5) {
      two$a <- c("+2","-6","4")
} else if (runif(1) >= 0.5 & runif(1) < 0.75) {
      two$a <- c("-4","+4","-6")
} else {
      two$a <- c("+3","-5","-3")
}
@

<<ejercicio03, echo=FALSE, results='hide'>>=
three <- list()

if (runif(1) < 0.25) {
      three$a <- c("2","-1"," ", "+2")
} else if (runif(1) >= 0.25 & runif(1) < 0.5) {
      three$a <- c("3","-2"," ","-1")
} else if (runif(1) >= 0.5 & runif(1) < 0.75) {
      three$a <- c("4","-9","2","+1")
} else {
      three$a <- c("5","-1","3","-2")
}
@

<<ejercicio04, echo=FALSE, results='hide'>>=
four <- list()

if (runif(1) < 0.25) {
      four$a <- c("3","-6","+8","-2","1")
} else if (runif(1) >= 0.25 & runif(1) < 0.5) {
      four$a <- c("1","-5","+6","-4","1")
} else if (runif(1) >= 0.5 & runif(1) < 0.75) {
      four$a <- c("2","+5","-14","-3","1")
} else {
      four$a <- c("4","-2","-8","-1","3")
}
@

<<ejercicio05, echo=FALSE, results='hide'>>=
five <- list()

if (runif(1) < 0.25) {
      five$a <- c("3","-","-6")
} else {
      five$a <- c("4","+2","+1")
}

if (runif(1) < 0.25) {
      five$b <- c("2"," ")
} else {
      five$b <- c("1","2")
}
@

\begin{enumerate}
      \item Resuelva las siguientes ecuaciones:
\begin{enumerate}
  \item $\Sexpr{one[[1]][1]}x^2 \Sexpr{one[[1]][2]}x\Sexpr{one[[1]][3]}=0$\\[15mm]
  \item $\Sexpr{one[[2]][1]}x^3 \Sexpr{one[[2]][2]}=0$\\[15mm]
\end{enumerate}
      
      \item Si $f$ es una funci\'{o}n tal que $f(x\Sexpr{two[[1]][1]})=x^2\Sexpr{two[[1]][2]}$. Calcule $f(\Sexpr{two[[1]][3]})$.\\[25mm]
      
      \item Determine el dominio de la siguiente funci\'{o}n: $y=\sqrt{\displaystyle\frac{\Sexpr{three[[1]][1]}x\Sexpr{three[[1]][2]}}{\Sexpr{three[[1]][3]}x\Sexpr{three[[1]][4]}}}$.\\[45mm]
      
      \item Halle el recorrido de la funci\'{o}n $y=\displaystyle\frac{\Sexpr{four[[1]][1]}}{x^2\Sexpr{four[[1]][2]}x\Sexpr{four[[1]][3]}}$, si $x\in [\Sexpr{four[[1]][4]}; \Sexpr{four[[1]][5]}]$.\\[40mm]
      
%       \item Para las siguientes funciones:
%       \[
%       f(x)= \frac{\Sexpr{five[[1]][1]}}{x^2\Sexpr{five[[1]][2]}x\Sexpr{five[[1]][3]}}
%       \qquad 
%       g(x)= \frac{\Sexpr{five[[2]][1]}}{\sqrt{\Sexpr{five[[2]][2]}x}}
%       \]
%       Calcule $f$o$g$.

\end{enumerate}

\end{document}