\documentclass[11pt,a4paper,oneside]{article}
\usepackage{amsmath,amsthm,amsfonts,amssymb}
\usepackage{pst-eucl,pstricks,pstricks-add}
%\usepackage[utf8]{inputenc}
%\usepackage[latin1]{inputenc}
\usepackage[spanish,activeacute]{babel}
\usepackage[a4paper,margin=2.5cm]{geometry}
\usepackage{times}
\usepackage[T1]{fontenc}
\usepackage{titlesec}
\usepackage{color}
\usepackage{url}
\usepackage{float}
\usepackage{cite}
\usepackage{graphicx}
\usepackage{multicol}
\usepackage{float}
\usepackage{lmodern}
\parindent=0mm


\begin{document}

\thispagestyle{empty}
{\sf
{\Large \scshape Escuela Polit\'{e}cnica Nacional} \hfill {\scshape 18 de Diciembre 2015}\\[3mm] 
{\scshape C\'{a}lculo en una variable \hfill Prueba $\#7$}\\[7mm]
{\scshape Nombre:} \rule{0.6\textwidth}{0.5pt}\qquad {\scshape Nro. lista:} \rule{0.1\textwidth}{0.5pt}\\
}

<<ejercicio01, echo=FALSE, results='hide'>>=
one <- sample(seq(1, 9, by=1), size=2, replace=FALSE)
@


\begin{enumerate}
      \item Calcule el siguiente límite: $\displaystyle \lim_{n\to \infty} \frac{1^2 + 2^2 + 3^2 + \ldots + (n-1)^2 + n^2}{n^2 + (n-1)n + \ldots + 3n + 2n + n}$\\[5cm]

      \item Use la prueba de la primera y segunda derivada para encontrar los extremos relativos, extremos absolutos, puntos de inflexión e intervalos de concavidad y convexidad de la función $f(x)=3x^4+2x^3-12x^2+4x+1$, en el intervalo $x\in [ -\frac{7}{2},3]$. Grafique.\\[13cm]
      
      \item Un círculo está inscrito en un cuadrado de lado $\ell$, como se muestra en la figura. ?`A qué razón cambia el área del círculo en el instante en que el lado del cuadrado mide 2 pulg y crece a razón de 4 pulg/min?.
      
      \begin{figure}[H]
      \centering
      \begin{pspicture}[showgrid=false](2,2)
      \pscircle[linecolor=red](1,1){0.98}
      \psframe[linecolor=blue](0,0)(2,2)
      \psline{|-|}(2.2,0)(2.2,2)
      \rput(2.4,1){$\ell$}
      \end{pspicture}
      \end{figure}
      
      \vspace{6cm}
      
      \item Se producirá una caja, abierta por la parte superior, de una pieza rectangular de cartón que mide 40 cm de largo por 30 cm de ancho. La caja puede cerrarse al cortar un cuadrado en cada esquina, al cortar sobre las líneas sólidas interiores y doblar luego el cartón por las líneas discontinuas. Exprese el volumen de la caja como una función de la variable indicada x. Encuentre las dimensiones de la caja con que se obtiene el volumen máximo. ?`Cuál es el volumen máximo?
      
      \begin{figure}[H]
      \centering
      \includegraphics[scale=0.45]{fig02.png}
      \end{figure}
      
      \vspace{8cm}
      
      \item Determinar las dimensiones del cono circular recto de mínimo volumen circunscrito a una esfera de radio R.
      
      \begin{figure}[H]
      \centering
      \begin{pspicture}[showgrid=false](4,3)
      \pscircle[linecolor=red](2,1){0.98}
      \psline[linecolor=blue](0.2,0)(3.8,0)(2,3)(0.2,0)
      \psline[linewidth=1.5pt]{->}(2,1)(2,0)
      \rput(2.2,0.5){\small R}
      \rput(2,3.3){\scriptsize Corte transversal}
      \end{pspicture}
      \end{figure}
      
\end{enumerate}

\end{document}