\documentclass[11pt,a4paper,oneside]{article}
\usepackage{amsmath,amsthm,amsfonts,amssymb}
\usepackage{pst-eucl,pstricks,pstricks-add}
%\usepackage[utf8]{inputenc}
%\usepackage[latin1]{inputenc}
\usepackage[spanish,activeacute]{babel}
\usepackage[a4paper,margin=2.5cm]{geometry}
\usepackage{times}
\usepackage[T1]{fontenc}
\usepackage{titlesec}
\usepackage{color}
\usepackage{url}
\usepackage{float}
\usepackage{cite}
\usepackage{graphicx}
\usepackage{multicol}
\usepackage{float}
\usepackage{lmodern}
\parindent=0mm


\begin{document}

\thispagestyle{empty}
{\sf
{\Large \scshape Escuela Polit\'{e}cnica Nacional} \hfill {\scshape 19 de Enero 2016}\\[3mm] 
{\scshape C\'{a}lculo en una variable \hfill Prueba $\#9$}\\[7mm]
{\scshape Nombre:} \rule{0.6\textwidth}{0.5pt}\qquad {\scshape Nro. lista:} \rule{0.1\textwidth}{0.5pt}\\
}

<<ejercicio01, echo=FALSE, results='hide'>>=
one <- sample(seq(1, 9, by=1), size=2, replace=FALSE)
@


\begin{enumerate}
      \item Evalúe las integrales definidas dadas.
      \begin{enumerate}
            \item {\scshape (1.5 Ptos.)} $\displaystyle \int\limits_{1}^{2} (x-x^{-3})\sqrt{x\sqrt[3]{x}}\ dx$\\[45mm]
            
            \item {\scshape (1.5 Ptos.)} $\displaystyle \int\limits_{-\infty}^{+\infty} e^{-|x|}\ dx$\\[45mm]
      \end{enumerate}
      
      \item Evalúe las integrales indefinidas dadas.
      \begin{enumerate}
            
            
            \item {\scshape (2 Ptos.)} $\displaystyle \int \frac{x^2+2x-6}{x^3-x}\ dx$\\[45mm]
            
            \newpage
            \item {\scshape (2 Ptos.)} $\displaystyle \int (x^2+2x+5)e^{-6x}\ dx$\\[50mm]
            
            \item {\scshape (2.5 Ptos.)} $\displaystyle \int \frac{x^2}{\sqrt{21+4x-x^2}}\ dx$\\[65mm]
            
            \item {\scshape (2.5 Ptos.)} $\displaystyle \int \frac{x^3+x^2+x+3}{x^4+4x^2+3}\ dx$\\[45mm]
            
      \end{enumerate}
      
      
      
\end{enumerate}

\end{document}